ensure oxttools.hunspell is passed a unicode string.
lxml parsing will return a string if the dictionary
word contains all ascii characters. So the results
will be inconsistent depending on each line's contents.

This was causing the following error:
Traceback (most recent call last):
  File "scripts/makeoxt", line 134, in <module>
    hun.addword(e.attrib['word'])
  File "/usr/local/lib/python2.7/dist-packages/
oxttools-0.1-py2.7.egg/oxttools/hunspell.py", line 22, in addword
    line = unicodedata.normalize('NFC', word)
TypeError: normalize() argument 2 must be unicode, not str